<?php
/**
 * coupon
 *
 * @copyright Copyright © 2019 Codilar Technologies. All rights reserved.
 * @author    arijit@codilar.com
 */
?>
<div class="block discount" id="block-discount" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ __('Apply Discount Code') ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
              action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset coupon<?= strlen($block->getCouponCode()) ? ' applied' : '' ?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="control">
                    <select id="coupon_code" name="coupon_code"
                            title="<?= /* @noEscape */ $block->escapeHtml(__("coupon_code"));?>"
                            class="validate-select">
                        <option value=""><?= $block->escapeHtml(__('Please select a coupon')) ?></option>
                        <?php foreach ($block->getCouponCodes() as $coupon): ?>
                            <option value="<?= $coupon->getCode() ?>" <?php if ($coupon->getCode() == $block->getCouponCode()): ?> selected <?php endif; ?> ><?= $coupon->getCode() ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action apply primary" type="button" value="<?= /* @escapeNotVerified */ __('Apply Discount') ?>">
                            <span><?= /* @escapeNotVerified */ __('Apply Discount') ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
